version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "security"
      - match:
          dependency_type: "production"
          update_type: "security"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
